// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aurora.proto
package aurora

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package
type GasPriceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasPriceRequest) Reset()         { *m = GasPriceRequest{} }
func (m *GasPriceRequest) String() string { return proto.CompactTextString(m) }
func (*GasPriceRequest) ProtoMessage()    {}
func (*GasPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c97969195a89af, []int{0}
}
func (m *GasPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasPriceRequest.Unmarshal(m, b)
}
func (m *GasPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasPriceRequest.Marshal(b, m, deterministic)
}
func (m *GasPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasPriceRequest.Merge(m, src)
}
func (m *GasPriceRequest) XXX_Size() int {
	return xxx_messageInfo_GasPriceRequest.Size(m)
}
func (m *GasPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GasPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GasPriceRequest proto.InternalMessageInfo

type GasPriceReply struct {
	Price                []byte   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasPriceReply) Reset()         { *m = GasPriceReply{} }
func (m *GasPriceReply) String() string { return proto.CompactTextString(m) }
func (*GasPriceReply) ProtoMessage()    {}
func (*GasPriceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c97969195a89af, []int{1}
}
func (m *GasPriceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasPriceReply.Unmarshal(m, b)
}
func (m *GasPriceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasPriceReply.Marshal(b, m, deterministic)
}
func (m *GasPriceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasPriceReply.Merge(m, src)
}
func (m *GasPriceReply) XXX_Size() int {
	return xxx_messageInfo_GasPriceReply.Size(m)
}
func (m *GasPriceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GasPriceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GasPriceReply proto.InternalMessageInfo

func (m *GasPriceReply) GetPrice() []byte {
	if m != nil {
		return m.Price
	}
	return nil
}

type ProtocolVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolVersionRequest) Reset()         { *m = ProtocolVersionRequest{} }
func (m *ProtocolVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ProtocolVersionRequest) ProtoMessage()    {}
func (*ProtocolVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c97969195a89af, []int{2}
}
func (m *ProtocolVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolVersionRequest.Unmarshal(m, b)
}
func (m *ProtocolVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolVersionRequest.Marshal(b, m, deterministic)
}
func (m *ProtocolVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolVersionRequest.Merge(m, src)
}
func (m *ProtocolVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ProtocolVersionRequest.Size(m)
}
func (m *ProtocolVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolVersionRequest proto.InternalMessageInfo

type ProtocolVersionReply struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolVersionReply) Reset()         { *m = ProtocolVersionReply{} }
func (m *ProtocolVersionReply) String() string { return proto.CompactTextString(m) }
func (*ProtocolVersionReply) ProtoMessage()    {}
func (*ProtocolVersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c97969195a89af, []int{3}
}
func (m *ProtocolVersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolVersionReply.Unmarshal(m, b)
}
func (m *ProtocolVersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolVersionReply.Marshal(b, m, deterministic)
}
func (m *ProtocolVersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolVersionReply.Merge(m, src)
}
func (m *ProtocolVersionReply) XXX_Size() int {
	return xxx_messageInfo_ProtocolVersionReply.Size(m)
}
func (m *ProtocolVersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolVersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolVersionReply proto.InternalMessageInfo

func (m *ProtocolVersionReply) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SyncingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncingRequest) Reset()         { *m = SyncingRequest{} }
func (m *SyncingRequest) String() string { return proto.CompactTextString(m) }
func (*SyncingRequest) ProtoMessage()    {}
func (*SyncingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c97969195a89af, []int{4}
}
func (m *SyncingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncingRequest.Unmarshal(m, b)
}
func (m *SyncingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncingRequest.Marshal(b, m, deterministic)
}
func (m *SyncingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncingRequest.Merge(m, src)
}
func (m *SyncingRequest) XXX_Size() int {
	return xxx_messageInfo_SyncingRequest.Size(m)
}
func (m *SyncingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncingRequest proto.InternalMessageInfo

type SyncingReply struct {
	Syncing              bool     `protobuf:"varint,1,opt,name=syncing,proto3" json:"syncing,omitempty"`
	StartingBlock        uint64   `protobuf:"fixed64,2,opt,name=startingBlock,proto3" json:"startingBlock,omitempty"`
	CurrentBlock         uint64   `protobuf:"fixed64,3,opt,name=currentBlock,proto3" json:"currentBlock,omitempty"`
	HighestBlock         uint64   `protobuf:"fixed64,4,opt,name=highestBlock,proto3" json:"highestBlock,omitempty"`
	PulledStates         uint64   `protobuf:"fixed64,5,opt,name=pulledStates,proto3" json:"pulledStates,omitempty"`
	KnownStates          uint64   `protobuf:"fixed64,6,opt,name=knownStates,proto3" json:"knownStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncingReply) Reset()         { *m = SyncingReply{} }
func (m *SyncingReply) String() string { return proto.CompactTextString(m) }
func (*SyncingReply) ProtoMessage()    {}
func (*SyncingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c97969195a89af, []int{5}
}
func (m *SyncingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncingReply.Unmarshal(m, b)
}
func (m *SyncingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncingReply.Marshal(b, m, deterministic)
}
func (m *SyncingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncingReply.Merge(m, src)
}
func (m *SyncingReply) XXX_Size() int {
	return xxx_messageInfo_SyncingReply.Size(m)
}
func (m *SyncingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncingReply.DiscardUnknown(m)
}

var xxx_messageInfo_SyncingReply proto.InternalMessageInfo

func (m *SyncingReply) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}
func (m *SyncingReply) GetStartingBlock() uint64 {
	if m != nil {
		return m.StartingBlock
	}
	return 0
}
func (m *SyncingReply) GetCurrentBlock() uint64 {
	if m != nil {
		return m.CurrentBlock
	}
	return 0
}
func (m *SyncingReply) GetHighestBlock() uint64 {
	if m != nil {
		return m.HighestBlock
	}
	return 0
}
func (m *SyncingReply) GetPulledStates() uint64 {
	if m != nil {
		return m.PulledStates
	}
	return 0
}
func (m *SyncingReply) GetKnownStates() uint64 {
	if m != nil {
		return m.KnownStates
	}
	return 0
}
func init() {
	proto.RegisterType((*GasPriceRequest)(nil), "aurora.GasPriceRequest")
	proto.RegisterType((*GasPriceReply)(nil), "aurora.GasPriceReply")
	proto.RegisterType((*ProtocolVersionRequest)(nil), "aurora.ProtocolVersionRequest")
	proto.RegisterType((*ProtocolVersionReply)(nil), "aurora.ProtocolVersionReply")
	proto.RegisterType((*SyncingRequest)(nil), "aurora.SyncingRequest")
	proto.RegisterType((*SyncingReply)(nil), "aurora.SyncingReply")
}
func init() { proto.RegisterFile("aurora.proto", fileDescriptor_22c97969195a89af) }

var fileDescriptor_22c97969195a89af = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xff, 0xfd, 0xeb, 0xd6, 0x65, 0xec, 0xba, 0x1a, 0xea, 0x5a, 0x8a, 0x48, 0x09, 0x0a,
	0x7b, 0x5a, 0x44, 0x4f, 0x82, 0x17, 0xbd, 0x78, 0x5d, 0xbb, 0xe0, 0xbd, 0xd6, 0xd0, 0x2d, 0x1b,
	0x92, 0x98, 0xa4, 0x4a, 0xbf, 0xa7, 0x47, 0x3f, 0x8c, 0x34, 0x69, 0xd6, 0xd6, 0xea, 0xf1, 0xbd,
	0xf9, 0xcd, 0x63, 0x98, 0x07, 0x41, 0x56, 0x49, 0x2e, 0xb3, 0x85, 0x90, 0x5c, 0x73, 0xe4, 0x5b,
	0x85, 0x8f, 0x60, 0xfa, 0x90, 0xa9, 0xa5, 0x2c, 0x73, 0x92, 0x92, 0xd7, 0x8a, 0x28, 0x8d, 0x2f,
	0x60, 0xf2, 0x6d, 0x09, 0x5a, 0xa3, 0x10, 0x46, 0xa2, 0x51, 0x91, 0x97, 0x78, 0xf3, 0x20, 0xb5,
	0x02, 0x47, 0x30, 0x5b, 0x36, 0x51, 0x39, 0xa7, 0x4f, 0x44, 0xaa, 0x92, 0x33, 0x17, 0x70, 0x09,
	0xe1, 0x60, 0xd2, 0xe4, 0x44, 0xb0, 0xf7, 0x66, 0xb5, 0x49, 0x1a, 0xa5, 0x4e, 0xe2, 0x43, 0x38,
	0x58, 0xd5, 0x2c, 0x2f, 0x59, 0xe1, 0x32, 0x3e, 0x3d, 0x08, 0xb6, 0x56, 0xbb, 0xac, 0xac, 0x36,
	0xcb, 0xe3, 0xd4, 0x49, 0x74, 0x0e, 0x13, 0xa5, 0x33, 0xa9, 0x4b, 0x56, 0xdc, 0x53, 0x9e, 0x6f,
	0xa2, 0xff, 0x89, 0x37, 0xf7, 0xd3, 0xbe, 0x89, 0x30, 0x04, 0x79, 0x25, 0x25, 0x61, 0xda, 0x42,
	0x3b, 0x06, 0xea, 0x79, 0x0d, 0xb3, 0x2e, 0x8b, 0x35, 0x51, 0x2d, 0xb3, 0x6b, 0x99, 0xae, 0xd7,
	0x30, 0xa2, 0xa2, 0x94, 0xbc, 0xac, 0x74, 0xa6, 0x89, 0x8a, 0x46, 0x96, 0xe9, 0x7a, 0x28, 0x81,
	0xfd, 0x0d, 0xe3, 0xef, 0xac, 0x45, 0x7c, 0x83, 0x74, 0xad, 0xab, 0x0f, 0x0f, 0xfc, 0x3b, 0xd3,
	0x00, 0xba, 0x85, 0x71, 0xd1, 0xbe, 0x1b, 0x9d, 0x2c, 0xda, 0x92, 0x7e, 0x74, 0x12, 0x1f, 0x0f,
	0x07, 0x82, 0xd6, 0xf8, 0x1f, 0x7a, 0x84, 0xa9, 0xe8, 0xff, 0x1a, 0x9d, 0x39, 0xf6, 0xf7, 0x7a,
	0xe2, 0xd3, 0x3f, 0xe7, 0x36, 0xf2, 0x66, 0xfb, 0x69, 0x34, 0x73, 0x68, 0xbf, 0x9d, 0x38, 0x1c,
	0xf8, 0x66, 0xf5, 0xd9, 0x37, 0xb7, 0x5c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x3a, 0x52,
	0x66, 0x6c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuroraClient is the client API for Aurora service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuroraClient interface {
	GasPrice(ctx context.Context, in *GasPriceRequest, opts ...grpc.CallOption) (*GasPriceReply, error)
	ProtocolVersion(ctx context.Context, in *ProtocolVersionRequest, opts ...grpc.CallOption) (*ProtocolVersionReply, error)
	Syncing(ctx context.Context, in *SyncingRequest, opts ...grpc.CallOption) (*SyncingReply, error)
}
type auroraClient struct {
	cc *grpc.ClientConn
}

func NewAuroraClient(cc *grpc.ClientConn) AuroraClient {
	return &auroraClient{cc}
}
func (c *auroraClient) GasPrice(ctx context.Context, in *GasPriceRequest, opts ...grpc.CallOption) (*GasPriceReply, error) {
	out := new(GasPriceReply)
	err := c.cc.Invoke(ctx, "/aurora.Aurora/gasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *auroraClient) ProtocolVersion(ctx context.Context, in *ProtocolVersionRequest, opts ...grpc.CallOption) (*ProtocolVersionReply, error) {
	out := new(ProtocolVersionReply)
	err := c.cc.Invoke(ctx, "/aurora.Aurora/protocolVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *auroraClient) Syncing(ctx context.Context, in *SyncingRequest, opts ...grpc.CallOption) (*SyncingReply, error) {
	out := new(SyncingReply)
	err := c.cc.Invoke(ctx, "/aurora.Aurora/syncing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuroraServer is the server API for Aurora service.
type AuroraServer interface {
	GasPrice(context.Context, *GasPriceRequest) (*GasPriceReply, error)
	ProtocolVersion(context.Context, *ProtocolVersionRequest) (*ProtocolVersionReply, error)
	Syncing(context.Context, *SyncingRequest) (*SyncingReply, error)
}

// UnimplementedAuroraServer can be embedded to have forward compatible implementations.
type UnimplementedAuroraServer struct {
}

func (*UnimplementedAuroraServer) GasPrice(ctx context.Context, req *GasPriceRequest) (*GasPriceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasPrice not implemented")
}
func (*UnimplementedAuroraServer) ProtocolVersion(ctx context.Context, req *ProtocolVersionRequest) (*ProtocolVersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProtocolVersion not implemented")
}
func (*UnimplementedAuroraServer) Syncing(ctx context.Context, req *SyncingRequest) (*SyncingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Syncing not implemented")
}
func RegisterAuroraServer(s *grpc.Server, srv AuroraServer) {
	s.RegisterService(&_Aurora_serviceDesc, srv)
}
func _Aurora_GasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuroraServer).GasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurora.Aurora/GasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuroraServer).GasPrice(ctx, req.(*GasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}
func _Aurora_ProtocolVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocolVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuroraServer).ProtocolVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurora.Aurora/ProtocolVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuroraServer).ProtocolVersion(ctx, req.(*ProtocolVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}
func _Aurora_Syncing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuroraServer).Syncing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurora.Aurora/Syncing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuroraServer).Syncing(ctx, req.(*SyncingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Aurora_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.Aurora",
	HandlerType: (*AuroraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "gasPrice",
			Handler:    _Aurora_GasPrice_Handler,
		},
		{
			MethodName: "protocolVersion",
			Handler:    _Aurora_ProtocolVersion_Handler,
		},
		{
			MethodName: "syncing",
			Handler:    _Aurora_Syncing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aurora.proto",
}
